import { User } from '../entities/user.entity';
import { Submission } from '../entities/submission.entity';

export interface IGrade {
    id: number;
    score: number;
    comment?: string;
    submissionId: number;
    criteriaId?: number;
    isAutoGenerated: boolean;
    isValidated: boolean;
    validatedBy?: number;
    aiJustification?: string;
    createdAt: Date;
    updatedAt: Date;
}

export interface ICreateGradeDto {
    score: number;
    comment?: string;
    submissionId: number;
    criteriaId?: number;
    isAutoGenerated: boolean;
    aiJustification?: string;
}

export interface IUpdateGradeDto {
    score?: number;
    comment?: string;
    isValidated?: boolean;
    validatedBy?: number;
}

export interface IGradeWithSubmissionDetails extends IGrade {
    submission: Submission;
}

export interface IGradeSummary {
    average: number;
    highest: number;
    lowest: number;
    median: number;
    distribution: {
        range: string;
        count: number;
    }[];
}

export interface IGradeValidationResult {
    success: boolean;
    message: string;
    grade?: IGrade;
}