export interface ISubmission {
    id: number;
    filePath: string;
    status: 'pending' | 'submitted' | 'graded';
    feedback?: string;
    studentId: number;
    examId: number;
    isLate: boolean;
    createdAt: Date;
    updatedAt: Date;
}

export interface ISubmissionWithRelations extends ISubmission {
    student?: {
        id: number;
        email: string;
    };
    exam?: {
        id: number;
        title: string;
        deadline?: Date;
    };
    grades?: Array<{
        id: number;
        value: number;
        isAutoGenerated: boolean;
    }>;
    plagiarismReports?: Array<{
        id: number;
        similarityScore: number;
        similarSubmissionIds: number[];
    }>;
}

export interface ICreateSubmissionDto {
    examId: number;
    studentId: number;
    filePath: string;
}

export interface IUpdateSubmissionDto {
    status?: 'pending' | 'submitted' | 'graded';
    feedback?: string;
}

export interface ISubmissionStats {
    totalSubmissions: number;
    pendingCount: number;
    submittedCount: number;
    gradedCount: number;
    lateSubmissionsCount: number;
    averageGrade?: number;
}

export interface ISubmissionFilters {
    examId?: number;
    studentId?: number;
    status?: 'pending' | 'submitted' | 'graded';
    isLate?: boolean;
}