import { Entity, PrimaryGeneratedColumn, Column, ManyToOne, JoinColumn } from 'typeorm';
import { Submission } from './submission.entity';

@Entity('grades')
export class Grade {
    @PrimaryGeneratedColumn()
    id!: number;

    @Column('float')
    score!: number;

    @Column({ type: 'text', nullable: true })
    comment?: string;

    @Column()
    submissionId!: number;

    @ManyToOne(() => Submission, submission => submission.grades)
    @JoinColumn({ name: 'submissionId' })
    submission!: Submission;

    @Column()
    criteriaId!: number;

    @Column({ default: false })
    isAutoGenerated!: boolean;
} 